### ISSUE TITLE
Logo For Responder

### ISSUE THREAD

**Issue by zularizal** [xxxrobinson/Responder#2]
Hi @xxxrobinson , I'm a graphic designer. I am interested in your project, so I want to contribute by creating a free logo for your project. What do you think?

**Comment by xxxrobinson** [comment]
Hello @zularizal, it would be my pleasure to have you on this project... Please proceed with designing the logo. Open a pull request with the changes you have in mind when you're done

**Comment by zularizal** [comment]
Hi @xxxrobinson , This is the logo for your project. The logo is inspired by a telephone and siren (meaning emergency). What do you think?
Select Left or Right?
If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/51873450-d1489080-238f-11e9-9150-5f06dbd95d24.png)

**Comment by xxxrobinson** [comment]
The one on the right is better... Please optimize the images for the different device sizes and open a pull request with your changes

**Comment by zularizal** [comment]
Hi @xxxrobinson, Sorry for a long time, I got sick a few days ago.

I uploaded the logo to the drive. Please check this link.
https://drive.google.com/open?id=1XkldTLlpIrKfMqfKL3B9awdnoTGfwISD

And also I have sent pull request. #3
